config/routes.rb
Rails.application.routes.draw do
  mount Blazer::Engine, at: "blazer"
  draw :madmin
  resources :reports, param: :uuid

  root "reports#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/query.rb
class Query < ApplicationRecord
  validates :name, :query, presence: true

  def to_sql(variables = {})
    ERB.new(query).result_with_hash(variables)
  end
end

app/models/query_execution.rb
class QueryExecution < ApplicationRecord
  belongs_to :report

  validates :result, presence: true
end

app/models/report.rb
class Report < ApplicationRecord
  attribute :uuid, :uuid, default: -> { SecureRandom.uuid }

  has_many :query_executions, dependent: :destroy

  def to_param
    uuid
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/madmin/application_controller.rb
module Madmin
  class ApplicationController < Madmin::BaseController
    # before_action :authenticate_admin_user

    # def authenticate_admin_user
      # TODO: Add your authentication logic here

      # For example, we could redirect if the user isn't an admin
      # redirect_to "/", alert: "Not authorized." unless user_signed_in? && current_user.admin?
    # end

    # Authenticate with Clearance
    # include Clearance::Controller
    # before_action :require_login

    # Authenticate with Devise
    # before_action :authenticate_user!

    # Authenticate with Basic Auth
    http_basic_authenticate_with(name: ENV.fetch("ADMIN_USER"), password: ENV.fetch("ADMIN_PASSWORD"))
  end
end

app/controllers/madmin/queries_controller.rb
module Madmin
  class QueriesController < Madmin::ResourceController
  end
end

app/controllers/madmin/query_executions_controller.rb
module Madmin
  class QueryExecutionsController < Madmin::ResourceController
  end
end

app/controllers/madmin/reports_controller.rb
module Madmin
  class ReportsController < Madmin::ResourceController
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def create
    # Create two tmp tables in DB (one for raw data and the other for processed data)
    # Read file and insert into tmp table
    # Process tmp table and insert into final tmp table
    # Execute queries against final tmp table
    # Delete tmp tables
    # Stores results and redirects to report page

    report = Report.create!
    sql_uuid = report.uuid.gsub('-', '_')
    connection = ApplicationRecord.connection_pool.checkout

    result = connection.execute(<<~SQL)
      create temporary table raw_data_#{sql_uuid} (
        row text
      );
    SQL

    result = connection.execute(<<~SQL)
      create temporary table processed_data_#{sql_uuid} (
        created_at timestamp,
        sender varchar(256),
        message text
      );
    SQL

    raw = connection.raw_connection
    raw.exec("copy raw_data_#{sql_uuid} from stdin")
    report_params[:chat_file].read.each_line do |line|
      raw.put_copy_data(line)
    end
    raw.put_copy_end
    while res = raw.get_result do; end

    result = connection.execute(<<~SQL)
      with processed as (
        select
          to_timestamp(
            unnest(regexp_match(row, '\\d+/\\d+/\\d+')) || ' ' || unnest(regexp_match(row, '\\d+:\\d+')),
            'MM/DD/YY HH24:MI'
          ) as created_at,
          unnest(regexp_match(row, '\\s-\\s(.*?):')) as sender,
          unnest(regexp_match(row, ':\\s(.+)\\Z')) as message
        from raw_data_#{sql_uuid}
      )

      insert into processed_data_#{sql_uuid}
      select *
      from processed
      where sender is not null
      and message not like 'null' -- These are instant photos
      and message not like '%<Media omitted>'
    SQL

    senders = connection.execute(<<~SQL)
      select
        sender
      from processed_data_#{sql_uuid}
      group by sender
      order by sender;
    SQL

    variables = {
      table: "processed_data_#{sql_uuid}",
      senders: senders.map { |row| row['sender'] }
    }

    Query.find_each do |query|
      query_sql = query.to_sql(variables)
      result = connection.execute(query_sql)
      QueryExecution.create!(
        query: query_sql,
        query_name: query.name,
        report: report,
        result: result
      )
    end

    ApplicationRecord.connection_pool.checkin(connection)

    redirect_to report
  ensure
    connection.execute(<<~SQL)
      drop table if exists raw_data_#{sql_uuid};
    SQL

    connection.execute(<<~SQL)
      drop table if exists processed_data_#{sql_uuid};
    SQL
  end

  def show
    @report = Report.find_by!(uuid: params[:uuid])
  end

  private

  def report_params
    params.require(:report).permit(:chat_file)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Whatswrapped</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5">
      <div class="flex items-center justify-center flex-col mx-auto mt-4 mb-4">
        <h1 class="text-lg sm:text-xl md:text-2xl font-bold text-gray-700 text-center">Tu <br>Whatsapp <br>Envuelto</h1>
      </div>

      <%= yield %>
    </main>
  </body>
</html>

app/views/query_executions/_query_execution.html.erb
<div class="bg-gray-50 py-4 px-2 rounded border-2 border-transparent hover:border-gray-100 prose">
  <p class="mb-2 px-2">
    <%= query_execution.query_name %>
  </p>
  <% if query_execution.result.is_a?(Array) %>
    <table class="table-auto mt-0">
      <tbody>
        <% query_execution.result.each do |row| %>
          <tr>
            <% row.sort.each do |(_key, value)| %>
              <td class="px-2"><%= value %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
      <strong class="font-bold">Error!</strong>
      <span class="block sm:inline"><%= query_execution.result %></span>
    </div>
  <% end %>
</div>

app/views/reports/new.html.erb
<%= form_with url: reports_path, scope: :report, class: "flex flex-col items-center" do |f| %>
  <%= f.file_field :chat_file, class: "bg-gray-100 p-2 rounded" %>

  <%= f.submit "Crear mi Whatsapp Wrapped", class: "rounded-md bg-black text-gray-100 py-2 px-4 mt-4 hover:bg-gray-800 cursor-pointer" %>
<% end %>

<article class="prose mt-6 p-6 bg-gray-100 rounded w-full mx-auto">
  <h4>
    ¿Cómo usar?
  </h4>
  <ol>
    <li>Descarga el backup de una conversación de Whatsapp. Sin archivos multimedia.
      <a href="https://faq.whatsapp.com/1180414079177245" target="_blank" class="text-blue-500 hover:underline">Ayuda.</a>
    </li>
    <li>Sube el archivo .txt aquí</li>
    <li>Crea tu Whatsapp envuelto</li>
  </ol>

  <h4>
    ¿Cómo funciona?
  </h4>
  <p>
    El .txt se procesa y se carga a una tabla temporal en la base de datos. Luego se ejecuta una colección de queries que extraen estadísticas de la conversación.
    Una vez que se termina de procesar, se borra la tabla temporal y se muestra el resultado. El resultado se guarda en la base de datos para que puedas volver a verlo.
  </p>
  <p>
    El archivo .txt subido no se guarda en ningún lado, solo se procesa y se borra.
  </p>
  <p>
    Las URLs del resultado pueden compartirse con otras personas.
  </p>
</article>

app/views/reports/show.html.erb
<%= link_to "Crear un nuevo envuelto", new_report_path, class: "flex justify-center text-gray-500 hover:underline mb-6" %>

<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
  <% @report.query_executions.each do |query_execution| %>
    <%= render query_execution %>
  <% end %>
</div>

<article class="prose mt-6 p-6 bg-gray-100 rounded w-full mx-auto mb-6">
  <p class="mb-0">
    Guardá este link para poder volver a verlo en cualquier momento.
  </p>
  <p class="py-1 px-2 rounded my-0 text-center break-words">
    <%= link_to report_url(@report), report_url(@report) %>
  </p>
</article>